### ISSUE TITLE
Buggy shell code

### ISSUE THREAD

**Issue by harkabeeparolus** [alexanderdamiani/pylinter#1]
Using `find` and `xargs` directly will break if any filenames contain spaces:
https://github.com/alexanderdamiani/pylinter/blob/f9e3029cf605992791a0ee1b44c152483bc9f3b9/entrypoint.sh#L24

This line should be changed from:
```bash
MYPY_ERRORS=$(find $1 -name "*.py" | xargs mypy $3)
```

To:
```bash
MYPY_ERRORS=$(find "$1" -name "*.py" -print0 | xargs -0 mypy "$3")
```

As a seasoned Bash and Unix shell programmer, I strongly recommend running the entire **entrypoint.sh** file through ShellCheck and fixing all issues with quoting in this script:
* https://www.shellcheck.net

**Comment by alexanderdamiani** [comment]
I appreciate the feedback. I went ahead and applied the path you mentioned as well as all recommended patches from the site you linked.

I've also added https://www.shellcheck.net to my toolbox for all future bash scripts that I'll write.
