### ISSUE TITLE
How can I exclude folder with mypy?

### ISSUE THREAD

**Issue by rreexxllii0310** [alexanderdamiani/pylinter#7]
Hi,
I would like to use mypy to check my code, but I have some .py files need to be excluded, they are under fixtures and static folder.

I have tried `mypy-flags: '--exclude ./(fixtures|static)/'`, but it didn't work.

Is there any example I can refer to?
That will be great, thank you!

**Comment by alexanderdamiani** [comment]
@rreexxllii0310 I have published a new release [v1.4.0](https://github.com/alexanderdamiani/pylinter/releases/tag/v1.4.0) which allows an argument `mypy-ignore-dirs-files` where you can pass either:

* individual files
* directories

to exclude from `mypy` checks.
